### ISSUE TITLE
mirobo 0.1.3 exceptions breaking the lights

### ISSUE THREAD

**Issue by mouth4war** [syssi/philipslight#1]
So I updated mirobo to 0.1.3 on my pi and ever since, there are new exceptions in the HASS log and the lights go to unknown state in the UI.

https://pastebin.com/QH9Jx6DG

>   File "/home/homeassistant/.homeassistant/custom_components/light/philipslight.py", line 166, in update
    state = self.light.status()
  File "/home/homeassistant/.homeassistant/custom_components/light/philipslight.py", line 112, in light
    from mirobo import Ceil
ImportError: cannot import name 'Ceil'

**Comment by syssi** [comment]
If the include called "Ceil" is missing a mirobo-python version < 0.1.3 is used. mirobo-python 0.1.3 is required.

**Comment by mouth4war** [comment]
Yes, I had recently updated HASS and that overwrote my locally modified xiaomi vacuum component to require 0.1.2 again. Fixed by changing that to 0.1.3. Thanks!

**Comment by syssi** [comment]
In future the components using python-mirobo are in sync. The official component will be called xiaomi_philipslight. Just follow: https://github.com/home-assistant/home-assistant/pull/9087
