### ISSUE TITLE
Extend platform services list

### ISSUE THREAD

**Issue by kuzyaka** [syssi/philipslight#12]
Hi

Is it possible to add light.xiaomi_miio_set_brightness / set_color_temperature services in order to control these parameters using automation?

I used these features successfully via "miceil" shell command for both philips.light.ceiling and philips.light.zyceiling

**Comment by syssi** [comment]
This is already possible. Just use the light.turn_on and provide some arguments (brightness, colortemp).

**Comment by kuzyaka** [comment]
Thank you
