### ISSUE TITLE
philips.light.mono1

### ISSUE THREAD

**Issue by yueqiumao** [syssi/philipslight#13]
philips.light.mono1

**Comment by syssi** [comment]
@yueqiumao Could you provide a link to the product?

**Comment by syssi** [comment]
I don't know anything about the device. It's the first generation of the desk lamp, right?

This commit should introduce a basic device support: https://github.com/syssi/philipslight/commit/6f509366757c8e28660873b6e38270e92faec27a

**Comment by yueqiumao** [comment]
https://www.mi.com/desklamp/

**Comment by syssi** [comment]
4000K neutral light.
