### ISSUE TITLE
Google Home is not able to detect XIaomi Philips Downlight if it is unavailable

### ISSUE THREAD

**Issue by terenceng81** [syssi/philipslight#27]
Hi syssi,

I am encountering an issue that Google Home is not able to detect unavailable Xiaomi-Philips downlight.

I turn the downlight on then it is able to detect and then I assigned to a room.

After that, I turn off the downlight (HA will show unavailable for downlight), and then turn it on again.

At this time, Google Home will detect this downlight again, somehow Google Home treats it as a new device.

Fine, I proceed to add the same downlight to the same room and I found there are repeated entries in the same room for the same downlight (Google Home App > Account > Settings > Assistant > Home Control > Rooms > Bedroom 1). 

I have tested official xiaomi_miio and your xiaomi_miio_philipslight, the result is same..

Seeking your kind assistance to find out is this suppose to be? Consistent power ON wont be a good solution for me as I do have a lot of physical wall switches controlling the power.

Million thanks in advance,
Terence

**Comment by syssi** [comment]
Could you provide your configuration.yaml of the component? Did you set the "model" there?

**Comment by terenceng81** [comment]
> Could you provide your configuration.yaml of the component? Did you set the "model" there?

Yes, I did set the model. anything wrong with the configuration?

light:
  - platform: xiaomi_miio_philipslight
    name: Philips Altar Downlight
    host: 192.168.8.177
    token: f9d6b085ad6b964db0d3958107761386
    model: philips.light.bulb
    
  - platform: xiaomi_miio
    name: Altar Downlight
    host: 192.168.8.177
    token: f9d6b085ad6b964db0d3958107761386
    model: philips.light.bulb

**Comment by terenceng81** [comment]
I should try it with "model: philips.light.downlight" instead of "philips.light.bulb", right?

**Comment by syssi** [comment]
Do you own the device and are you able to provide some testing? I would like to implement/support the device.

**Comment by syssi** [comment]
Yes the model is called `philips.light.downlight`.

**Comment by terenceng81** [comment]
It seems okay for 

> Do you own the device and are you able to provide some testing? I would like to implement/support the device.

Thank you for your reply syssi.

Yes, I own the device perhaps almost all xiaomi products.

I can provide you the remote access to my HA or you could let me know what I can help for the implementation/support?

**Comment by syssi** [comment]
Let's talk about the new device support here: https://github.com/syssi/philipslight/issues/24
