### ISSUE TITLE
Add support to HACS

### ISSUE THREAD

**Issue by jokerigno** [syssi/philipslight#31]
HI,

I use this custom component for a year now and few days ago I started to notice that my bedside lamps are no longer availabe on HA.

Then I checked that you updated your amazing component and I was wondering: why don't you add support to HACS in order to make easier the update process?

Thank you in advance

**Comment by syssi** [comment]
The progress & evolution of the Home Assistant community is just to fast for me. :-)

**Comment by syssi** [comment]
I would happily provide HACS support.

**Comment by syssi** [comment]
Done.

**Comment by jokerigno** [comment]
Hi,

I switched to last version via hacs and now lights are no longer avaialble.

This is the last working config:

```
  - platform: xiaomi_miio_philipslight
    name: Comodino Marco
    host: 192.168.2.14
    token: c9f25848730a2fd5ef34a2016c898430

```
and this is the new config:

```
  - platform: xiaomi_miio_philipslight
    name: Comodino Marco
    host: 192.168.2.14
    token: c9f25848730a2fd5ef34a2016c898430
    model: philips.light.moonlight
```

At boot I only see this error: 

> Logger: homeassistant.helpers.service
> Source: helpers/service.py:447
> First occurred: 13:02:28 (1 occurrences)
> Last logged: 13:02:28
> 
> Unable to find referenced entities light.comodino_marco

Thank you

**Comment by jokerigno** [comment]
@syssi I wrote here the issue because I think it's something related to HACS. If you prefer I can open a new one.

**Comment by syssi** [comment]
@jokerigno I assume the entity id is already bound to the xiaomi_miio component. Could you check your entity list? I assume entitity has a new entity id if you use `xiaomi_miio_philipslight`.

**Comment by jokerigno** [comment]
Oh well it was so easy! Thank you!
