### ISSUE TITLE
Add yeelink.light.color5 support

### ISSUE THREAD

**Issue by HepoH3** [syssi/philipslight#38]
Looking in server log I can see following message:

> Logger: homeassistant.components.xiaomi_miio.light
> Source: components/xiaomi_miio/light.py:194
> Integration: Xiaomi Miio (documentation, issues)
> First occurred: 11:44:31 (1 occurrences)
> Last logged: 11:44:31
> 
> Unsupported device found! Please create an issue at https://github.com/syssi/philipslight/issues and provide the following data: yeelink.light.color5

**Comment by syssi** [comment]
Did you try the `yeelight` component instead?

**Comment by HepoH3** [comment]
> 
> 
> Did you try the `yeelight` component instead?

Yeah, sorry, I forgot to close this issue.
The problem was that Yeelight does not support new xiaomi bulbs in the official yeelight app. Because of this, I could not turn on the LAN mode on the light bulb. Fortunately, I found out about an unofficial app that can work with this light bulb.
