### ISSUE TITLE
Integration not available in HACS

### ISSUE THREAD

**Issue by TeoTN** [syssi/philipslight#44]
The integration is not available in HACS anymore. I've tried looking for the phrase "Xiaomi Philips Lights Integration" and a few similar ones and it's not found. It's not listed [here](https://hacs.xyz/docs/default_repositories) either. Could you please consider adding it to HACS? It's quite convenient.

**Comment by syssi** [comment]
Requirements:

https://github.com/home-assistant/brands/pull/2143
https://github.com/home-assistant/wheels-custom-integrations/pull/228

Finally as soon the requirements are met:

https://github.com/hacs/default/pull/767
