### ISSUE TITLE
Device supported?

### ISSUE THREAD

**Issue by DARKFiB3R** [syssi/philipslight#49]
Hi there,

Can you please let me know if this device is supported?

Thank you.

https://imgur.com/OuA6rrb
https://imgur.com/0ZQ8bKl
https://imgur.com/b4PHYs6
https://imgur.com/aR1NY5V
https://imgur.com/7AB4pXL
https://imgur.com/mEmG2TF
https://imgur.com/WMUneYE

**Comment by syssi** [comment]
Sorry, I don't know any details about the device.
