### ISSUE TITLE
Ceiling Light server response time

### ISSUE THREAD

**Issue by DARKFiB3R** [syssi/philipslight#59]
I'm in the UK, but I (have to?) use the China server for my ceiling light.

Some times it is very slow to respond, so much so, that Alexa anounces that it hasn't responded at all, but then it does  turn on/off afterwards anyway.

Is there anything I can do to improve the response time?

Thanks.

**Comment by syssi** [comment]
1. If you don't use the Mi Home / yeelight app you could try to block the internet access for your cloud devices. If the connection gets dropped very early the device is a bit faster.
2. If you want to gain more speed: Flash the device with ESPHome / alternative firmware.  But keep in mind: The remote control isn't supported and you have to control your lamp via HA always.

**Comment by DARKFiB3R** [comment]
How do I do option 1?

Is there a 3rd party remote I could use with esphome?

Is removing the PCB and replacing it with some sort of zigbee module an option?

Thanks for your advice. Have a nice Christmas.

**Comment by syssi** [comment]
Option 1: Yes.

As soon the ESPHome node is connected to your HA instance you could use any supported remote. If you are looking for a standalone solution: I don't know.

I don't recommend to replace the WiFi controller by a ZigBee module. It's hard to replicate all features of the device (f.e. the night light mode).

**Comment by syssi** [comment]
Merry Christmas! 🎄

**Comment by DARKFiB3R** [comment]
So I gave the lights a static IP, and then blocked them.

The Xiaomi app says they are offline.

Unfortunately they are still intermittently slow to respond.

So... ESPHome. I don't see a repository for my ceiling light. Can you point me in the right direction?

Thanks.

**Comment by syssi** [comment]
Which device do you own? Please use `miiocli device info` to retrieve the model identifier and may be some hint about the used `mcu`.

**Comment by DARKFiB3R** [comment]
Which device do you own? Please use miiocli device info to retrieve the model identifier and may be some hint about the used mcu.

I've never used miiocli before, and not sure how.

I did use Xiaomi Cloud Tokens Extractor.

platform: xiaomi_miio_philipslight
model: philips.light.ceiling

**Comment by syssi** [comment]
It's easier to use a linux host. Please boot some Ubuntu machine or SSH to some raspberry pi and use this command to install python-miio:

```
pip3 install python-miio
```

If `pip3` isn't available please install the missing package:

```
apt-get install python3-pip
```
