### ISSUE TITLE
Question: How does it compare with `Xiaomi Miio`?

### ISSUE THREAD

**Issue by sameersbn** [syssi/philipslight#61]
I have a bunch of  `Philips Zhirui Downlight` lights at my home and I'm using the `Xiaomi Miio` which I think is present in HA by default. I am curious to know if using this integration has any benefits over the `Xiaomi Miio`

I am sorry if this has been answered before. Thanks!

**Comment by syssi** [comment]
If your device is supported by the official Home Assistant Core integration called `xiaomi_miio` this custom component doesn't have any benefit for you!
