### ISSUE TITLE
FIVE UV Sterilization Lamp frequently breaks down... ...

### ISSUE THREAD

**Issue by Henry-Tan76** [syssi/philipslight#64]
Actually I bought about 12 FIVE UV lamps and tried 5 lamps which I have since in Singapore made four exchanges with Singapore's Honor due to lamps not working within a month's normal use.

There was some... ... issues when seeking Honor.

Anyway, 2 lamps' bulbs 'burst' at the covered top of the lamps, 2 lamps switched off AUTOMATICALLY after shining UV for a few seconds, then went beep beep beep and that was it.

This time, the lamp that breaks down right today is a replacement for the first broken batch of 2 lamps... ... Replacement on 23 Dec 2023, so... ... now it worked for a little over 1 month, and the replacement lamp is down. It shone for like a few seconds, and went off to send a long beep beep beep each (longer than the count down individual beep) and won't shine anymore.

I checked the bulb, I can't see any cracks... ... and I am not sure if the internal circuit is the fault, and this is not the first time I have encountered this strange problem. The other 4 lamps are still functioning... ... as per normal use. 

Anyone knows how to troubleshoot or if anyone has (naughtily) hacked the lamp so it only shines for a few seconds?

Thanks.

Anyone from XiaoMi or FIVE can help? 

This is a big issue because I planned for 30 lamps but after trying 5, only 2 are still working from the day they are bought without breaking down. This is gross!

From Henry Tan, Singapore.

**Comment by syssi** [comment]
Sorry I cannot help here.
